### ISSUE TITLE
Fix broken OIDC login with Archivematica

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/archivematica-infrastructure#111]
When users try to log in with OpenID Connect, they get an error:

```
10.50.2.214 - - [31/Oct/2022:10:29:55 +0000] "GET /oidc/callback/?code=[redacted]&state=[redacted]&session_state=[redacted] HTTP/1.1" 500 2832 "https://archivematica.wellcomecollection.org/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "78.149.89.147"
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 185, in _get_response
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/mozilla_django_oidc/views.py", line 99, in get
    self.user = auth.authenticate(**kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
File "/usr/local/lib/python3.6/dist-packages/mozilla_django_oidc/auth.py", line 286, in authenticate
    return self.get_or_create_user(access_token, id_token, payload)
File "/usr/local/lib/python3.6/dist-packages/mozilla_django_oidc/auth.py", line 307, in get_or_create_user
    user_info = self.get_userinfo(access_token, id_token, payload)
File "/src/src/dashboard/src/components/accounts/backends.py", line 53, in get_userinfo
id_info = json.loads(JWS.from_compact(id_token).payload.decode("utf-8"))
File "/usr/local/lib/python3.6/dist-packages/josepy/jws.py", line 304, in from_compact
    protected, payload, signature = compact.split(b'.')
TypeError: must be str or None, not bytes
ERROR     2022-10-31 10:29:55  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /oidc/callback/
```

We should work out what's going on here.

**Comment by alexwlchan** [comment]
The error comes from this line in the Archivematica code:

```python
id_info = json.loads(JWS.from_compact(id_token).payload.decode("utf-8"))
```

so I added a line to print the repr of the `id_token` value, which turns out to have type `string`.

If you look at `JWS.from_compact`, that wants type `bytes`: https://github.com/certbot/josepy/blob/f2d41f0a2aa5a1d7a623c7176fb1c89632d7c71e/src/josepy/jws.py#L322

So I think we're missing an `.encode()` call on this line.

**Comment by alexwlchan** [comment]
Here's a handy logging link: https://logging.wellcomecollection.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'94746ad0-81c5-11eb-b41a-c9fd641654c0',key:ecs_cluster,negate:!f,params:(query:archivematica-staging),type:phrase),query:(match_phrase:(ecs_cluster:archivematica-staging))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'94746ad0-81c5-11eb-b41a-c9fd641654c0',key:service_name,negate:!f,params:(query:am-staging-dashboard),type:phrase),query:(match_phrase:(service_name:am-staging-dashboard)))),index:'94746ad0-81c5-11eb-b41a-c9fd641654c0',interval:auto,query:(language:kuery,query:'not%20log:%22*HTTP%2F1.1%5C%22%20200*%22%20and%20not%20log:%22*HTTP%2F1.1%5C%22%20302*%22'),sort:!(!('@timestamp',desc)))

**Comment by alexwlchan** [comment]
So if I encode the `id_token` so it's `bytes`, I get a different error:

```
ERROR     2022-10-31 11:36:18  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /oidc/callback/
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/mozilla_django_oidc/views.py", line 99, in get
    self.user = auth.authenticate(**kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
File "/usr/local/lib/python3.6/dist-packages/mozilla_django_oidc/auth.py", line 286, in authenticate
    return self.get_or_create_user(access_token, id_token, payload)
File "/usr/local/lib/python3.6/dist-packages/mozilla_django_oidc/auth.py", line 307, in get_or_create_user
    user_info = self.get_userinfo(access_token, id_token, payload)
File "/src/src/dashboard/src/components/accounts/backends.py", line 64, in get_userinfo
    info[user_attr] = id_info[oidc_attr]
KeyError: 'email'
```

I'm not sure what's up with that – I'm going to log the ID info and see what happens.

**Comment by alexwlchan** [comment]
These are the keys we get:

```
dict_keys(['aud', 'iss', 'iat', 'nbf', 'exp', 'nonce', 'rh', 'sub', 'tid', 'uti', 'ver'])
```

Bit confused now. 🤷‍♀️
